### ISSUE TITLE
When a publisher removes a publisher feed, we should detect that and disable the publisher feed.

### ISSUE THREAD

**Issue by odscjames** [openactive/conformance-services#18]
eg, If https://onlinebooking.1610.org.uk/OpenActive/ suddenly stopped publishing any "Slot" feed

**Comment by nickevansuk** [comment]
What do you mean by "removes a feed"?

- **Feed reference removed from the dataset site** - that feed has gone and should no longer be harvested, but other feeds should continue to be harvested.
- **The dataset site itself is returning a 404** - The publisher has unpublished their data, and all data relating to that publisher should be purged immediately, in case of GDPR breach or similar (Note some systems such as Gladstone are designed to return a 404 from the dataset site if a user presses the "disable open data feeds" button within their booking system, so this is by design)
- **A feed page returns a status of anything other than a [200, 429, or 503](https://openactive.io/realtime-paged-data-exchange/#http-status-codes)** - feed is in an inconsistent state, and is displaying symptoms of an error that should be fixed. Suggest harvesting is restarted from the beginning of the feed the following day, when the errors may have been resolved. If this happens ideally an error would be shown on the status page saying e.g. "Harvesting halted at {pageUrl}, which returned status code {statusCode}".

Note often a feed will often return e.g. a 500 on only one particular RPDE page due to some conditional logic, which is why it's so helpful to surface the erroneous {pageUrl}. 

As an example, https://opendata.leisurecloud.live/api/feeds/1610-live-slots is now working again

**Comment by odscjames** [comment]
For this issue, explicitly:

> Feed reference removed from the dataset site - that feed has gone and should no longer be harvested, but other feeds specified in the dataset site should continue to be harvested.

eg, If https://onlinebooking.1610.org.uk/OpenActive/ suddenly stopped publishing any "Slot" feed

The existing code on the main branch won't do this, so this

I will put the rest in other issues.

But Q, if a feed is stopped publishing; should we purge all data we have for that feed straight away? (the GDPR issues mentioned)

**Comment by nickevansuk** [comment]
Ah right, so for this specific case for that specific publisher: likely that the Slots feed had issues with the CDN and RPDE proxy so temporarily unpublished itself. It then automatically reappeared after proxy issues were resolved.

If a feed is removed from the dataset site then the feed contents should be purged. If it gets readded to the dataset site the feed contents should again be harvested from the beginning (same as if any new feed is added to any dataset site).

**Comment by odscjames** [comment]
> Ah right, so for this specific case for that specific publisher: likely that the Slots feed had issues with the CDN and RPDE proxy so temporarily unpublished itself. It then automatically reappeared after proxy issues were resolved.

My example was totally made up :-)

We will look into the purging rule you say.

**Comment by odscjames** [comment]
Question for this and #39: How fast should we purge all data? As soon as we see it missing? A few days after we see it missing?

We are concerned that temporary errors might take a server down for an hour, but in that hour we notice and delete everything, and then have to start from scratch.

**Comment by odscjames** [comment]
Realised: We can't purge data in the sql `DELETE` sense - because then our RPDE interface won't publish delete flags to consumers, and consumers will still have the data we are trying to clear urgently! We need to do soft deletes; `UPDATE raw/normalised SET deleted=TRUE, data=NULL`. That will still clear the data out of our store.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Establish what we need to do if a publisher stops publishing either a particular feed or OA data entirely](https://trello.com/c/Rj6Bfn4A/90-establish-what-we-need-to-do-if-a-publisher-stops-publishing-either-a-particular-feed-or-oa-data-entirely)

**Comment by robredpath** [comment]
Discussed with @thill-odi . We shouldn't actively delete data from a publisher that stops publishing, but we shouldn't seek to retain it (eg if we need to wipe the db for some reason) either.

The exception is if there's a takedown request, which we'll deal with separately.

**Comment by odscjames** [comment]
Ok, thanks. But re-opening as I would expect we still would want to flag the fact a publisher has removed a publisher feed somehow, even just a comment on the new status page?

**Comment by odscjames** [comment]
Ah, also see https://github.com/openactive/conformance-services/issues/39#issuecomment-657665225 - could @thill-odi confirm what should happen here?
